<?php

/**
 * Created by PhpStorm.
 * User: xubin
 * Date: 2021/3/24
 * Time: 18:03
 */

return [
    0 => [
        'app_name'                    => 'America', // 应用名称
        'price_index'                 => 15,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '-7',  // 时区
        'platform'                    => 0,
        'complete_order_adjust_token' => 'qzchqy',  // adjust下单事件key
        'adjust_app_token'            => 'aphu3ezyd728',    // adjust应用key
        'adjust_s2s_secret'           => 'aa3863e997915201244e4bcf87fe582c',    // adjust s2s 安全密钥
        'android_package_name'        => 'com.lmmobi.lereader',     // android包名
        'ios_package_name'            => 'com.lmmobi.lereader',     // ios包名
        'url'                         => 'lereader://lereader_main', //deeplink
        'red_envelope'                => 7,
        'api_test_host'               => 'http://abroad-api.ad6755.com/',
        'api_host'                    => 'https://api.kwmobi.com/',
        'umeng_app_key'               => '60bf5a728d6cd512500b9e96',
        'language'                    => 1,
        'name'                        => 'lereader',
        'admin_test_host'             => 'https://abroad-admin.ad6755.com/',
        'admin_host'                  => 'https://admin.kwmobi.com/',
        'fb_pre'                      => ['Le'], // facebook账户前缀
        'ratio'                       => '0.01427', // 繁体：0.01833港元 一个币 英文：0.01427美元一个币
        'redis_db'                    => 0,
        'GA4_json_path'               => public_path('google/449fbc9c2c38.json'), // 服务账号json文件路径
        'GA4_property_id'             => '268119320', // 服务账号property_id
    ],
    1 => [
        'app_name'                    => 'HongKong',
        'price_index'                 => 40,
        'max_price'                   => 80,
        'min_price'                   => 14,
        'timezone'                    => '+8',
        'platform'                    => 1,
        'complete_order_adjust_token' => 'vfnrhv',
        'adjust_app_token'            => 'wmfk2kyx0um8',
        'adjust_s2s_secret'           => 'e72f5f9c2a83343c2e2eaaeef58a1a53',
        'android_package_name'        => 'com.youshuge.lebook.abord',
        'ios_package_name'            => 'com.leshu.hwbook',
        'url'                         => 'lebook://lebook_main',
        'red_envelope'                => 2,
        'api_test_host'               => 'http://abroadapi.ad6755.com',
        'api_host'                    => 'https://api.lmmobi.com',
        'umeng_app_key'               => '60c9b94626a57f1018275ddb',
        'language'                    => 0,
        'name'                        => '乐书小说',
        'admin_test_host'             => 'http://hkadmin-test.ad6755.com/',
        'admin_host'                  => 'https://hkadmin.kwmobi.com/',
        'fb_pre'                      => ['乐书', '樂書'],
        'ratio'                       => '0.01833',
        'redis_db'                    => 0,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    2 => [
        'app_name'                    => 'XiangYue',
        'price_index'                 => 40,
        'max_price'                   => 80,
        'min_price'                   => 14,
        'timezone'                    => '+8',
        'platform'                    => 2,
        'complete_order_adjust_token' => 'wj86kb',
        'adjust_app_token'            => '7w0ic6kgia2o',
        'adjust_s2s_secret'           => '7285038876a38cb2228e51946b33b82c',
        'android_package_name'        => '',
        'ios_package_name'            => 'com.readerBook.enjoybookcity',
        'url'                         => 'lelenovel://lelenovel_main',
        'red_envelope'                => 3,
        'api_test_host'               => 'http://apitest.inertia4.com',
        'api_host'                    => 'https://api.inertia4.com',
        'umeng_app_key'               => '',
        'language'                    => 0,
        'name'                        => '享阅书城',
        'admin_test_host'             => 'http://hkadmin-test-vtest.ad6755.com/',
        'admin_host'                  => 'https://xyadmin.kwmobi.com/',
        'fb_pre'                      => ['享閱'],
        'ratio'                       => '0.01833',
        'redis_db'                    => 1,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    3 => [
        'app_name'                    => 'KeeNovel', // 应用名称
        'price_index'                 => 17,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '-7',  // 时区
        'platform'                    => 3,
        'complete_order_adjust_token' => 'yojtrs',  // adjust下单事件key
        'adjust_app_token'            => '2au96t3p6y2o',    // adjust应用key
        'adjust_s2s_secret'           => 'b410a1a0ff27a2c9b8327a9a021cd47f',    // adjust s2s 安全密钥
        'android_package_name'        => '',     // android包名
        'ios_package_name'            => 'com.ForeignReader.Keenovel',     // ios包名
        'url'                         => '', //deeplink
        'red_envelope'                => 7,
        'api_test_host'               => 'http://abroad-api.ad6755.com/',
        'api_host'                    => 'https://api.keenovel.com/',
        'umeng_app_key'               => '',
        'language'                    => 1,
        'name'                        => 'KeeNovel',
        'admin_test_host'             => 'https://abroad-admin.ad6755.com/',
        'admin_host'                  => 'https://keenovel.kwmobi.com/',
        'fb_pre'                      => ['Kee'],
        'ratio'                       => '0.01427',
        'redis_db'                    => 3,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    4 => [
        'app_name'                    => 'DuniaBaca', // 印尼应用名称
        'price_index'                 => 5,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '+7',  // 时区
        'platform'                    => 4,
        'complete_order_adjust_token' => 'ibjran',  // adjust下单事件key
        'adjust_app_token'            => 'uupdmpai4mps',    // adjust应用key
        'adjust_s2s_secret'           => 'f1ab2d0cabfe04180768bc7e1dc67392',    // adjust s2s 安全密钥
        'android_package_name'        => 'com.bacadunia.duniabaca',     // android包名
        'ios_package_name'            => '',     // ios包名
        'url'                         => 'duniabaca://duniabaca_main', //deeplink
        'red_envelope'                => 3,
        'api_test_host'               => '',
        'api_host'                    => 'https://api.duniabacas.com/',
        'umeng_app_key'               => '',
        'language'                    => 2,
        'name'                        => 'DuniaBaca',
        'admin_test_host'             => '',
        'admin_host'                  => 'https://duniabacas.kwmobi.com/',
        'fb_pre'                      => [],
        'ratio'                       => '',
        'redis_db'                    => 5,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    5 => [
        'app_name'                    => 'Caminovela', // 应用名称
        'price_index'                 => 18,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '-7',  // 时区
        'platform'                    => 5,
        'complete_order_adjust_token' => 'd262su',  // adjust下单事件key
        'adjust_app_token'            => 'azuhx290gem8',    // adjust应用key
        'adjust_s2s_secret'           => '7d06d91e45416f2d4309c147076a3aa1',    // adjust s2s 安全密钥
        'android_package_name'        => 'com.gogomaster.caminovela',     // android包名
        'ios_package_name'            => 'com.spanishReader.Caminovela',     // ios包名
        'url'                         => 'caminovela://caminovela_main', //deeplink
        'red_envelope'                => 7,
        'api_test_host'               => '',
        'api_host'                    => 'https://api.caminovela.com/',
        'umeng_app_key'               => '',
        'language'                    => 3,
        'name'                        => 'Caminovela',
        'admin_test_host'             => '',
        'admin_host'                  => 'https://caminovela.kwmobi.com/',
        'fb_pre'                      => ['Cam'],
        'ratio'                       => '0.01427',
        'redis_db'                    => 4,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    6 => [
        'app_name'                    => 'UpNovel', // 应用名称
        'price_index'                 => 15,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '-7',  // 时区
        'platform'                    => 6,
        'complete_order_adjust_token' => 'j8022w',  // adjust下单事件key
        'adjust_app_token'            => 'q1zfq29xo4jk',    // adjust应用key
        'adjust_s2s_secret'           => '4ec91ad469562fbd081312f6b67de767',    // adjust s2s 安全密钥
        'android_package_name'        => 'com.mbreader.noveltxt',     // android包名
        'ios_package_name'            => '',     // ios包名
        'url'                         => 'upnovel://upnovel_main', //deeplink
        'red_envelope'                => 3,
        'api_test_host'               => '',
        'api_host'                    => '',
        'umeng_app_key'               => '',
        'language'                    => 1,
        'name'                        => 'UpNovel',
        'admin_test_host'             => '',
        'admin_host'                  => 'https://upnovels.kwmobi.com/',
        'fb_pre'                      => [],
        'ratio'                       => '0.01427',
        'redis_db'                    => 5,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    7 => [ //英文马甲包
        'app_name'                    => 'Novelenders', // 应用名称
        'price_index'                 => 17,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '-7',  // 时区
        'platform'                    => 7,
        'complete_order_adjust_token' => 'ocoya3',  // adjust下单事件key
        'adjust_app_token'            => 'c7acbf9cijnk',    // adjust应用key
        'adjust_s2s_secret'           => '5d301ce33079bfaf9704498654941eb7',    // adjust s2s 安全密钥
        'android_package_name'        => 'com.novelmobl.novelenders',     // android包名
        'ios_package_name'            => 'com.novelenderBook.novelenders',     // ios包名
        'url'                         => 'novelenders://novelenders_main', //deeplink
        'red_envelope'                => 3,
        'api_test_host'               => '',
        'api_host'                    => '',
        'umeng_app_key'               => '',
        'language'                    => 1,
        'name'                        => 'Novelenders',
        'admin_test_host'             => '',
        'admin_host'                  => 'https://Novelenders.kwmobi.com/',
        'fb_pre'                      => ['Ned'],
        'ratio'                       => '0.01427',
        'redis_db'                    => 7,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
    8 => [
        'app_name'                    => 'DiNovel', // 印尼应用名称
        'price_index'                 => 5,    // 千字价格
        'max_price'                   => 80,    // 章节最高价格
        'min_price'                   => 14,    // 章节最低价格
        'timezone'                    => '+7',  // 时区
        'platform'                    => 8,
        'complete_order_adjust_token' => 'mh91sb',  // adjust下单事件key
        'adjust_app_token'            => 'osurn63lcnpc',    // adjust应用key
        'adjust_s2s_secret'           => '51a86f9d766b2038df94916a5c2ebc90',    // adjust s2s 安全密钥
        'android_package_name'        => 'com.dinovel.pembaca',     // android包名
        'ios_package_name'            => '',     // ios包名
        'url'                         => 'dinovel://dunivel_main', //deeplink
        'red_envelope'                => 3,
        'api_test_host'               => '',
        'api_host'                    => 'https://api.dinovels.com/',
        'umeng_app_key'               => '',
        'language'                    => 2,
        'name'                        => 'DiNovel',
        'admin_test_host'             => '',
        'admin_host'                  => 'https://dinovel.kwmobi.com/',
        'fb_pre'                      => [],
        'ratio'                       => '',
        'redis_db'                    => 6,
        'GA4_json_path'               => '',
        'GA4_property_id'             => '',
    ],
];
